#!/bin/bash
fileExt=$1
sourceFolder=$2
targetFolder=$3

if [[ -z $fileExt ]] || [[ -z $sourceFolder ]] || [[ -z $targetFolder ]]; then
echo "ERROR!"
echo "Example: $0 scs \"$HOME/games/ets2/mods\" \"$HOME/games/mods\" "
exit 1
else
find "$sourceFolder" -name "*.$fileExt" -type f -exec cp -f {} "$targetFolder" \;
fi