#!/bin/bash
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"

declare -A COLORS=(
    [Black]='\033[0;30m' [DarkBlue]='\033[0;34m' [DarkGreen]='\033[0;32m' [DarkCyan]='\033[0;36m'
    [DarkRed]='\033[0;31m' [DarkMagenta]='\033[0;35m' [DarkYellow]='\033[0;33m' [Gray]='\033[0;37m'
    [DarkGray]='\033[1;30m' [Blue]='\033[1;34m' [Green]='\033[1;32m' [Cyan]='\033[1;36m'
    [Red]='\033[1;31m' [Magenta]='\033[1;35m' [Yellow]='\033[1;33m' [White]='\033[1;37m'
    [NoColor]='\033[0m'
)

if [[ "$(uname -s)" != "Linux" ]]; then
    echo -e "${COLORS[Red]}This script is designed for Linux.${COLORS[NoColor]}"
    exit 1
fi

function is_command() { command -v "$1" &>/dev/null; }

function check_root() {
    if [[ $EUID -eq 0 ]]; then
        echo -e "${COLORS[Red]}You must not run this script as root.${COLORS[NoColor]}"
        exit 1
    fi
}

function verify_password() {
    echo -n -e "${COLORS[Cyan]}Password for ${COLORS[Red]}root:${COLORS[NoColor]} "
    read -s user_password
    echo -e "\n${COLORS[Yellow]}Verifying password...${COLORS[NoColor]}"
    echo "$user_password" | sudo -S true &>/dev/null && return 0 || {
        echo -e "${COLORS[Red]}Incorrect password.${COLORS[NoColor]}"
        exit 1
    }
}

function SUDO() {
    echo "$user_password" | sudo -S "$@"
}

function cleanup() {
    unset user_password
    sudo --reset-timestamp
}
trap cleanup EXIT

function check_internet() {
    curl -s --head http://www.google.com | grep "200" &>/dev/null || {
        echo -e "${COLORS[Red]}No Internet connection.${COLORS[NoColor]}"
        exit 1
    }
}

FONT_DIR="/usr/local/share/fonts/truetype"

function localdisk_windowsfont {
    WindowsDiskPath="/run/media/$USER/OS"
    WINDOWS_FONT_DIR="$WindowsDiskPath/Windows/Fonts/"

    SUDO mkdir -p "$FONT_DIR/WindowsFonts"
    if [ -d "$WINDOWS_FONT_DIR" ]; then
        SUDO find "$WINDOWS_FONT_DIR" -type f \( -name "*.ttf" -o -name "*.otf" \) -exec cp -f {} "$FONT_DIR/WindowsFonts" \;
        SUDO fc-cache -f -v
        fc-cache -f -v
    else
        echo -e "${Red}The directory was not found, so the operation was not completed.  (${WINDOWS_FONT_DIR}) ${NoColor}"
        exit
    fi
}

function applefont {
    local BaseURL tempdir dmgfile pkgdir
    BaseURL="https://devimages-cdn.apple.com/design/resources/download/"
    Fonts=("SF-Pro.dmg" "SF-Compact.dmg" "SF-Mono.dmg" "NY.dmg")
    tempdir=$(mktemp -d)

    sudo mkdir -p "$FONT_DIR/AppleFonts"
    cd "$tempdir" || exit

    for Font in "${Fonts[@]}"; do
        curl -L "${BaseURL}${Font}" -o "${Font}"
    done

    for dmgfile in *.dmg; do
        7z e "${dmgfile}" -y -o"$tempdir"
        7z x -txar *.pkg -y
        pkgdir=$(find . -type d -name "*.pkg" | head -n 1)
        cd "$pkgdir" || continue
        7z x Payload -y
        7z x Payload~ -y 2>/dev/null
        sudo mv Library/Fonts/* "$FONT_DIR/AppleFonts"
    done
    rm -rf "$tempdir"
}

copy_proton() {
    search_directories=("$HOME/Games/Prefix" "$HOME/WineData")
    source_fonts="/usr/local/share/fonts/truetype/WindowsFonts"

    for dir in "${search_directories[@]}"; do
        find "$dir" -type f -name "system.ini" | while IFS= read -r system_ini; do
            parent_dir=$(dirname "$system_ini")

            if [[ "$parent_dir" =~ ^.*/pfx/drive_c/windows$ ]]; then
                echo -e "${COLORS[Green]}${parent_dir} Directory Found!${COLORS[NoColor]}"

                if [ -L "$parent_dir/Fonts" ]; then
                    mv -f "$parent_dir/Fonts" "$parent_dir/Fonts.wine"
                fi

                mkdir -p "$parent_dir/Fonts" && rm -rf "$parent_dir/Fonts/"*
                cp -a "$source_fonts/." "$parent_dir/Fonts/"
                echo -e "${COLORS[Blue]}Font Copied: ${COLORS[Cyan]}${parent_dir}/Fonts${COLORS[NoColor]}"
            fi
        done
    done
}

download_meslo() {
    MESLO_URL=$(curl -s "https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest" | jq -r ".assets[] | select(.name | test(\"Meslo.zip\")) | .browser_download_url")
    test -d "/tmp/Meslo.zip" && SUDO rm -rf "/tmp/Meslo.zip"
    test -d "$FONT_DIR/Meslo" && SUDO rm -rf "$FONT_DIR/Meslo"
    sleep 3
    curl -L "$MESLO_URL" -o /tmp/Meslo.zip
    SUDO mkdir -p "$FONT_DIR/Meslo"
    SUDO unzip "/tmp/Meslo.zip" -d "$FONT_DIR/Meslo"
}

function HelpFunction {
    echo -e "${COLORS[Cyan]}Usage:${COLORS[NoColor]}"
    echo "  ${SCRIPT_NAME} [options]"
    echo -e "\n${COLORS[Cyan]}Options:${COLORS[NoColor]}"
    echo -e "  -h, --help               Show this help message"
    echo -e "  -a, --applefont          Download SF fonts from the internet and copy them to: $FONT_DIR/AppleFonts"
    echo -e "  -lw, --localwindows      Copy installed Windows fonts (OTF/TTF) from $WindowsDiskPath/$WINDOWS_FONT_DIR to $FONT_DIR/WindowsFonts"
    echo -e "  -p, --proton             Copy fonts from $FONT_DIR/WindowsFonts to Steam's compatdata directories for Proton"
    echo -e "  -m, --meslofont          Download Meslo Fonts"
    echo -e "  update                   Update the script itself"
    exit 0
}

for arg in "$@"; do
    case "${arg,,}" in
    -h | --help)
        HelpFunction
        exit 0
        ;;
    update)
        curl -L "https://raw.githubusercontent.com/herrwinfried/myconfig/linux/data/scripts/$SCRIPT_NAME" -o "$SCRIPT_DIR/$SCRIPT_NAME"
        exit 0
        ;;
    -a | --applefont)
        check_root
        verify_password
        check_internet
        applefont
        ;;
    -lw | --localwindows)
        check_root
        verify_password
        localdisk_windowsfont
        ;;
    -p | --proton)
        check_root
        verify_password
        copy_proton
        ;;
    -m | --meslofont)
        check_root
        verify_password
        download_meslo
        ;;
    *) echo -e "${COLORS[Red]}Invalid argument: $arg${COLORS[NoColor]}" ;;
    esac
done
