#!/bin/bash
if [ -x "$(command -v gamemoderun)" ]; then
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only gamemoderun "$@"
else
echo "gamemoderun not found..."
fi