#!/bin/bash
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"

fileExt=$1
sourceFolder=$2
targetFolder=$3

declare -A COLORS=(
    [Black]='\033[0;30m' [DarkBlue]='\033[0;34m' [DarkGreen]='\033[0;32m' [DarkCyan]='\033[0;36m'
    [DarkRed]='\033[0;31m' [DarkMagenta]='\033[0;35m' [DarkYellow]='\033[0;33m' [Gray]='\033[0;37m'
    [DarkGray]='\033[1;30m' [Blue]='\033[1;34m' [Green]='\033[1;32m' [Cyan]='\033[1;36m'
    [Red]='\033[1;31m' [Magenta]='\033[1;35m' [Yellow]='\033[1;33m' [White]='\033[1;37m'
    [NoColor]='\033[0m'
)


if [[ "$(uname -s)" != "Linux" ]]; then
    echo -e "${COLORS[Red]}This script is designed for Linux.${COLORS[NoColor]}"
    exit 1
fi

if [[ -z $fileExt ]] || [[ -z $sourceFolder ]] || [[ -z $targetFolder ]]; then
echo "${COLORS[Red]}ERROR!${COLORS[NoColor]}"
echo "Example: $0 {File Extension} {Source Directory} {Target Directory}"
exit 1
else
find "$sourceFolder" -name "*.$fileExt" -type f -exec ln -sf {} "$targetFolder" \;
fi