#!/bin/bash
GetScriptDir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
GetScriptName=$(basename "${BASH_SOURCE[0]}")

Black='\033[0;30m'
DarkBlue='\033[0;34m'
DarkGreen='\033[0;32m'
DarkCyan='\033[0;36m'
DarkRed='\033[0;31m'
DarkMagenta='\033[0;35m'
DarkYellow='\033[0;33m'
Gray='\033[0;37m'
DarkGray='\033[1;30m'
Blue='\033[1;34m'
Green='\033[1;32m'
Cyan='\033[1;36m'
Red='\033[1;31m'
Magenta='\033[1;35m'
Yellow='\033[1;33m'
White='\033[1;37m'
NoColor='\033[0m' # No Color

USER_PASSWORD=""
function rootpassword {
if [[ $EUID -eq 0 ]]; then
     echo -e "${Red}You must not be Super User/Root.${NoColor}"
   exit 1
fi
sudo --reset-timestamp
# shellcheck disable=SC2162
echo -n -e "${Cyan}Password for ${Red}root:${NoColor} "
# shellcheck disable=SC2162
read -s USER_PASSWORD
echo -e "\n${Yellow}Password checking...${NoColor}"
if echo "$USER_PASSWORD" | sudo -S true >/dev/null 2>&1; then
    echo -e "${Green}Password verified.${NoColor}\n"
    function SUDO {
        # shellcheck disable=SC2317
        echo "$USER_PASSWORD" | sudo -S "$@"
    }
else
    echo -e "${Red}Password could not be verified ${NoColor}\n"
    rootpassword
fi  
}
function rootpassword_end {
    unset USER_PASSWORD
    sudo --reset-timestamp
}

search_recursive() {
    SUDO find "$1" -type f -name "$2" 2>/dev/null
}

search_directories=("/mnt" "/run/media/$USER" "$HOME" "/root")


rootpassword

for directory in "${search_directories[@]}"; do
    if found_files=$(search_recursive "$directory" "libraryfolder.vdf"); then
        for file in $found_files; do
            parent_dir=$(dirname "$file")
        echo -e "${Green}${parent_dir} Directory Found!${NoColor}"
        if [ -d "$parent_dir/steamapps" ]; then
            if [ ! -d "$HOME/Games/SteamData" ]; then
                    mkdir -p "$HOME/Games/SteamData"
            fi
                ln -sf "$parent_dir/steamapps/compatdata" "$HOME/Games/SteamData"
                echo -e "${DarkBlue}${parent_dir}/steamapps/compatdata ${Cyan}Symbolic Link Created!${NoColor}"

        else
            echo -e "${DarkBlue}${parent_dir} Directory:${DarkRed} Couldn't find anything to meet the conditions!${NoColor}"
            fi
        done
    else
        echo -e "${DarkBlue}${directory} Directory:${Red} Couldn't find anything to meet the conditions!${NoColor}"
    fi
done

rootpassword_end