#!/bin/bash

distroselect=$(lsb_release -d | awk -F"\t" '{print $2}')
if [ "$distroselect" == "openSUSE Tumbleweed" ]; then

PackageName="zypper --gpg-auto-import-keys"
PackageInstall="install -y -l"
UpdateArg="dup -y -l --force-resolution"
PackageRemove="remove -y"

function install {

sudo $PackageName $UpdateArg
sudo $PackageName $PackageInstall curl tar libicu73 libopenssl1_0_0 jq

pwshcore=$(curl -s "https://api.github.com/repos/PowerShell/PowerShell/releases/latest" | jq -r ".assets[] | select(.name | test(\"linux-x64.tar.gz\")) | .browser_download_url")

curl -L $pwshcore -o /tmp/powershell.tar.gz
sudo mkdir -p /opt/microsoft/powershell
sudo tar -xzf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/
sudo ln -s /opt/microsoft/powershell/pwsh /usr/bin/pwsh
sudo chmod +x /usr/bin/pwsh
}

function uninstall {

if [ -d "/tmp/powershell.tar.gz" ]; then
sudo rm -rf /tmp/powershell*
fi

if [ -d "/opt/microsoft/powershell" ]; then
sudo rm -rf /opt/microsoft/powershell
fi
sleep 3
}

uninstall
install
fi