#!/bin/bash

function sudoreq {
    sudo -v || {
        echo -e $red"Cancel..."$white
        exit 1
    }
}

function sudofinish {
    sudo --reset-timestamp
}

function checkcommand {
    if type -P $1 >/dev/null; then
        return 0
    else
        return 1
    fi
}

. /etc/os-release

OS_Name=$NAME
OS_Version=$VERSION
distro=$(echo $OS_Name $OS_VERSION | tr '[:upper:]' '[:lower:]')

function openSUSETW_ALIAS {
    # ZYPPER OR DNF
    #   0        1
    SUSE_TYPE=0
    if ! checkcommand dnf; then
        SUSE_TYPE=0
    fi
    ################

    if [ $SUSE_TYPE -eq 1 ]; then
        if ! checkcommand dnf; then
            SUSE_TYPE=0
        fi
    fi

    if [ $SUSE_TYPE -eq 0 ]; then
        PackagePrep="zypper"
        Package="$PackagePrep --gpg-auto-import-keys --no-gpg-checks"
        PackageUpdate="dup -y -l"
        PackageRefresh="refresh"

        PackageRemove="rm -u -y"
        PackageInstall="in --allow-unsigned-rpm -y -l"

    elif [ $SUSE_TYPE -eq 1 ]; then
        PackagePrep="dnf"
        Package="$PackagePrep --nogpgcheck"
        PackageUpdate="dup -y"
        PackageRefresh="makecache"

        PackageRemove="remove -y"
        PackageInstall="install -y"
    fi
}

function fedora_ALIAS {
    PackagePrep="dnf"
    Package="$PackagePrep --nogpgcheck"
    PackageUpdate="update -y"
    PackageRefresh="makecache"

    PackageRemove="remove -y"
    PackageInstall="install -y"
}

if [[ $distro = *opensuse\ tumbleweed* ]]; then
    openSUSETW_ALIAS
elif [[ $distro = *fedora\ linux* ]]; then
    fedora_ALIAS
else
    echo "It is currently not compatible with your Operating system." && exit 1
fi

function install {
    sudo $Package $PackageUpdate

    if [[ $distro = *opensuse\ tumbleweed* ]]; then
        sudo $Package $PackageInstall curl tar libicu73 libopenssl1_0_0 jq
    elif [[ $distro = *fedora\ linux* ]]; then
        sudo $Package $PackageInstall curl tar libicu openssl-libs jq
    fi

    pwshcore=$(curl -s "https://api.github.com/repos/PowerShell/PowerShell/releases/latest" | jq -r ".assets[] | select(.name | test(\"linux-x64.tar.gz\")) | .browser_download_url")

    curl -L $pwshcore -o /tmp/powershell.tar.gz
    sudo mkdir -p /opt/microsoft/powershell
    sudo tar -xzf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/
    sudo ln -s /opt/microsoft/powershell/pwsh /usr/bin/pwsh
    sudo chmod +x /usr/bin/pwsh
}

function uninstall {
    if [ -d "/tmp/powershell.tar.gz" ]; then
        sudo rm -rf /tmp/powershell*
    fi

    if [ -d "/opt/microsoft/powershell" ]; then
        sudo rm -rf /opt/microsoft/powershell
    fi

    sleep 3
}

sudoreq

uninstall
install

sudofinish