#!/bin/bash
if [ -x "$(command -v flatpak)" ]; then
    if flatpak list --columns=application | grep -q "com.valvesoftware.Steam"; then
        flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam-wrapper com.valvesoftware.Steam "$@"
    fi
elif rpm -q steam-1.0.0.78-2.1.x86_64; then
    /usr/bin/steam "$@"
else
    echo "Not Found Steam"
fi
