#!/bin/bash
if [ -x "$(command -v flatpak)" ]; then
    if flatpak list --columns=application | grep -q "com.valvesoftware.Steam"; then

    etc_os_release=$(md5sum /etc/os-release)
    my_os_release=$(md5sum "$HOME/.var/me/os-release")
    if [ "$etc_os_release" != "$my_os_release" ]; then
         cp -f /etc/os-release "$HOME/.var/me/os-release"
    fi
    unset etc_os_release
    unset my_os_release
    if ! [ $# -eq 0 ]; then
        flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam-wrapper com.valvesoftware.Steam
    else 
        flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam-wrapper com.valvesoftware.Steam "$@"
    fi

    fi
if rpm -q steam || [ -f /usr/bin/steam ]; then
    if ! [ $# -eq 0 ]; then
        /usr/bin/steam 
    else 
        /usr/bin/steam "$@"
    fi

elif [ -f /usr/games/steam ]; then
    if ! [ $# -eq 0 ]; then
        /usr/games/steam
    else 
        /usr/games/steam "$@"
    fi
else
    echo "Not Found Steam"
fi
fi