#!/bin/bash

COMPAT_DATA_DIR="$HOME/Games/Prefix/compatdata"

export STEAM_COMPAT_DATA_PATH="$COMPAT_DATA_DIR/scssoftware"
export STEAM_COMPAT_CLIENT_INSTALL_PATH="$HOME/.steam/steam"

PROTON="$STEAM_COMPAT_CLIENT_INSTALL_PATH/steamapps/common/Proton - Experimental/proton"
#PROTON="$STEAM_COMPAT_CLIENT_INSTALL_PATH/compatibilitytools.d/GE-Proton10-18/proton"
TRUCKERSMP_INSTALLER="$HOME/Downloads/TruckersMP-Setup.exe"
TRUCKERSMP_LAUNCHER="$STEAM_COMPAT_DATA_PATH/pfx/drive_c/users/steamuser/AppData/Local/TruckersMP/TruckersMP-Launcher.exe"

for APPID in 227300 270880; do
    DIR="$COMPAT_DATA_DIR/$APPID"
    [ -d "$DIR" ] && [ ! -L "$DIR" ] && mv "$DIR" "$DIR.old"
    [ ! -L "$DIR" ] && ln -s "$STEAM_COMPAT_DATA_PATH" "$DIR"
done

if [ ! -d "$STEAM_COMPAT_DATA_PATH" ] || [ -z "$(ls -A "$STEAM_COMPAT_DATA_PATH")" ]; then
    mkdir -p "$STEAM_COMPAT_DATA_PATH"
    PROTON_LOG=1 "$PROTON" run "$TRUCKERSMP_INSTALLER"
    exit 1;
fi


PROTON_LOG=1 "$PROTON" waitforexitandrun "$TRUCKERSMP_LAUNCHER" && echo %command%
