#!/bin/bash

GetScriptDir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
GetScriptName=$(basename "${BASH_SOURCE[0]}")
BOARD_VENDOR=$(cat /sys/class/dmi/id/board_vendor 2>/dev/null | tr '[:upper:]' '[:lower:]')

declare -A COLORS=(
    [Black]='\033[0;30m' [DarkBlue]='\033[0;34m' [DarkGreen]='\033[0;32m' [DarkCyan]='\033[0;36m'
    [DarkRed]='\033[0;31m' [DarkMagenta]='\033[0;35m' [DarkYellow]='\033[0;33m' [Gray]='\033[0;37m'
    [DarkGray]='\033[1;30m' [Blue]='\033[1;34m' [Green]='\033[1;32m' [Cyan]='\033[1;36m'
    [Red]='\033[1;31m' [Magenta]='\033[1;35m' [Yellow]='\033[1;33m' [White]='\033[1;37m'
    [NoColor]='\033[0m'
)


if [[ "$(uname -s)" != "Linux" ]]; then
    echo -e "${COLORS[Red]}This script is designed for Linux.${COLORS[NoColor]}"
    exit 1
fi

function is_command() { command -v "$1" &>/dev/null; }

function check_root() {
    if [[ $EUID -eq 0 ]]; then
        echo -e "${COLORS[Red]}You must not run this script as root.${COLORS[NoColor]}"
        exit 1
    fi
}

function verify_password() {
    echo -n -e "${COLORS[Cyan]}Password for ${COLORS[Red]}root:${COLORS[NoColor]} "
    read -s user_password
    echo -e "\n${COLORS[Yellow]}Verifying password...${COLORS[NoColor]}"
    echo "$user_password" | sudo -S true &>/dev/null && return 0 || {
        echo -e "${COLORS[Red]}Incorrect password.${COLORS[NoColor]}"
        exit 1
    }
}

function SUDO() {
    echo "$user_password" | sudo -S "$@"
}

function cleanup() {
    unset user_password
    sudo --reset-timestamp
}
trap cleanup EXIT

function check_internet() {
    curl -s --head http://www.google.com | grep "200" &>/dev/null || {
        echo -e "${COLORS[Red]}No Internet connection.${COLORS[NoColor]}"
        exit 1
    }
}

. /etc/os-release
DISTRO=$(echo "$NAME" | tr '[:upper:]' '[:lower:]')

for cmd in curl tar jq; do
    if ! is_command "$cmd"; then
        echo -e "${COLORS[Red]}Not Found $cmd${COLORS[NoColor]}"
        exit 1
    fi
done

if [[ "$BOARD_VENDOR" == *"asus"* ]]; then
    check_root
    check_internet
    verify_password

    asustheme=$(curl -s "https://api.github.com/repos/AdisonCavani/distro-grub-themes/releases/latest" | jq -r ".assets[] | select(.name | test(\"asus.tar\")) | .browser_download_url")
    DEFAULT_GRUB_THEME="GRUB_THEME=/boot/grub2/themes/openSUSE/theme.txt"

    if [ -d "/tmp/asus.tar" ]; then
        SUDO rm -rf /tmp/asus*
    fi

    if [ -d "/boot/grub2.d/themes/asus" ]; then
        echo -e "${COLORS[Yellow]}Removing the /boot/grub2.d/themes/asus folder..${COLORS[NoColor]}"
        SUDO rm -rf /boot/grub2.d/themes/asus
        current_grub_theme=$(grep -E "^GRUB_THEME=" /etc/default/grub)
        if [ "$current_grub_theme" != "$DEFAULT_GRUB_THEME" ]; then
            SUDO sed -i "s|^GRUB_THEME=.*|$DEFAULT_GRUB_THEME|" /etc/default/grub
            echo -e "${COLORS[Green]}GRUB_THEME value successfully reverted to its initial state.${COLORS[NoColor]}"
        fi
    fi
    sleep 3

    curl -L "$asustheme" -o "/tmp/asus.tar"
    SUDO mkdir -p /boot/grub2.d/themes/asus
    SUDO tar -xf "/tmp/asus.tar" -C /boot/grub2.d/themes/asus
    new_grub_theme="GRUB_THEME=/boot/grub2.d/themes/asus/theme.txt"
    current_grub_theme=$(grep -E "^GRUB_THEME=" /etc/default/grub)

    if [ "$current_grub_theme" != "$new_grub_theme" ]; then
        SUDO sed -i "s|^GRUB_THEME=.*|$new_grub_theme|" /etc/default/grub
        SUDO grub2-mkconfig -o /boot/grub2/grub.cfg
        echo -e "${COLORS[Green]}GRUB_THEME value successfully modified and Grub updated.${COLORS[NoColor]}"
    fi
else
echo -e "${COLORS[Red]}No grub theme found.${COLORS[NoColor]}"
fi