#!/bin/bash

sudo zypper in -y libguestfs libguestfs-appliance

MountDirectory=$HOME/.mount/WSLopensuse
WindowsUser=$USER
WindowsDiskPath=/run/media/$USER/OS

echo "mkdir -p $MountDirectory"
mkdir -p "$MountDirectory"
sleep 5
echo ""
echo guestmount --add "$WindowsDiskPath/Users/$WindowsUser/AppData/Local/Packages/46932SUSE.openSUSETumbleweed_022rs5jcyhyac/LocalState/ext4.vhdx" --inspector --rw "$MountDirectory"
guestmount --add "$WindowsDiskPath/Users/$WindowsUser/AppData/Local/Packages/46932SUSE.openSUSETumbleweed_022rs5jcyhyac/LocalState/ext4.vhdx" --inspector --rw "$MountDirectory"
sleep 5